### PR TITLE
beam_elements.py: fixing `from_line` method...

### PR DESCRIPTION
**Pull request by aoeftiger**
...which is a class method and wrongfully did not return an instance

(the `append_line` method does not return self and probably
should not, therefore instantiate the class inside `from_line`,
append the provided line arg, and then return the instance)

### CODE REVIEW

**Comment by rdemaria** [comment]
I think it is also fine to return self for methods that change the internal state (to implement the so-called method chaining style...)

**Comment by martinschwinzerl** [comment]
Thank you for reporting this issue! 

I would propose to rather modify `append_line()` and return `self` from there as this would be more consistent with the general direction our API has taken for (purely) state-modifying members. I'm currently cleaning up something else but would provide a patch along those lines very shortly, if there is agreement

**Comment by aoeftiger** [comment]
Sure, let's keep it consistent, I agree!

**Comment by aoeftiger** [comment]
This version works for me and should consist with your API, i.e. `append_line` returns the current instance (`self`)

**Review by martinschwinzerl — APPROVED** [review]

**Pull request merged**
